# Generated by Django 6.1.1 on 2026-09-17 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغو\u200cشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('assigned_technicians', models.ManyToManyField(blank=True, limit_choices_to={'role': 'employee'}, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='تکنیسین\u200cهای مسئول')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_client', to='core.party', verbose_name='طرف\u200cحساب (واسطه/کارفرمای مستقیم ما)')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_contractor', to='core.party', verbose_name='پیمانکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.location', verbose_name='موقعیت مکانی پروژه')),
                ('property_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_owner', to='core.party', verbose_name='صاحب ملک / کارفرمای اصلی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='projects_pr_status_b6b628_idx')],
            },
        ),
    ]
