# Generated by Django 6.1.1 on 2026-09-19 11:51

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0003_partycontact_remove_historicalparty_linked_user_and_more'),
        ('projects', '0002_historicalproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('is_default', models.BooleanField(default=False, verbose_name='قالب پیش\u200cفرض')),
            ],
            options={
                'verbose_name': 'قالب گردش\u200cکار',
                'verbose_name_plural': 'قالب\u200cهای گردش\u200cکار',
            },
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='property_owner',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='property_owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ دقیق اتمام'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='کد پروژه'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ عقد قرارداد'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تخمینی پایان'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='extra_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه\u200cهای مازاد دستی (تومان)'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='guaranteed_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تضمین پایان قرارداد'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='installation_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه نصب (تومان)'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_client': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.party', verbose_name='صاحب ملک / کارفرمای اصلی'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='partner',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_partner': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.party', verbose_name='شریک تجاری'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه ارسال (تومان)'),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ دقیق اتمام'),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='کد پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ عقد قرارداد'),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تخمینی پایان'),
        ),
        migrations.AddField(
            model_name='project',
            name='extra_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه\u200cهای مازاد دستی (تومان)'),
        ),
        migrations.AddField(
            model_name='project',
            name='guaranteed_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تضمین پایان قرارداد'),
        ),
        migrations.AddField(
            model_name='project',
            name='installation_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه نصب (تومان)'),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_client': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_owner', to='core.party', verbose_name='صاحب ملک / کارفرمای اصلی'),
        ),
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(default=1, limit_choices_to={'is_partner': True}, on_delete=django.db.models.deletion.PROTECT, related_name='projects_as_partner', to='core.party', verbose_name='شریک تجاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه ارسال (تومان)'),
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='قیمت فروش واحد (تومان)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_usages', to='catalog.item', verbose_name='کالا')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_materials', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'اضافه متریال پروژه',
                'verbose_name_plural': 'اضافه\u200cمتریال\u200cهای پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('contractor', 'پیمانکار'), ('electrician', 'برق\u200cکار'), ('assembler', 'مونتاژکار'), ('supervisor', 'ناظر'), ('other', 'سایر')], max_length=20, verbose_name='نقش')),
                ('agreed_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه توافق\u200cشده (تومان)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_participations', to='core.party', verbose_name='طرف\u200cحساب بیرونی')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='projects.project', verbose_name='پروژه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_participations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر داخلی')),
            ],
            options={
                'verbose_name': 'عامل اجرایی پروژه',
                'verbose_name_plural': 'عوامل اجرایی پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='قیمت واحد (تومان) - مخصوص همین پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='projects.project', verbose_name='پروژه')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_lines', to='catalog.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'خدمت پروژه',
                'verbose_name_plural': 'خدمات پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ترتیب')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مرحله (کپی\u200cشده)')),
                ('client_label', models.CharField(blank=True, max_length=150, verbose_name='عنوان نمایشی برای کارفرما')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('waiting_approval', 'در انتظار تایید'), ('rejected', 'رد شده / نیازمند اصلاح'), ('done', 'انجام\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('client_visible', models.BooleanField(default=True, verbose_name='قابل نمایش به کارفرما')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اتمام')),
                ('rejection_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد دفعات رد شدن')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to=settings.AUTH_USER_MODEL, verbose_name='مسئول انجام')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stages', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'مرحله پروژه',
                'verbose_name_plural': 'مراحل پروژه',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('file', models.FileField(upload_to=projects.models.project_file_upload_path, verbose_name='فایل')),
                ('kind', models.CharField(choices=[('dwg', 'فایل اتوکد (DWG)'), ('pdf', 'PDF'), ('image', 'عکس'), ('other', 'سایر')], max_length=20, verbose_name='نوع فایل')),
                ('version', models.PositiveSmallIntegerField(blank=True, verbose_name='شماره نسخه')),
                ('is_current', models.BooleanField(default=True, verbose_name='آخرین نسخه')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='projects.projectfile', verbose_name='جایگزین نسخه')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projectstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'فایل پروژه',
                'verbose_name_plural': 'فایل\u200cهای پروژه',
                'ordering': ['stage', '-version'],
            },
        ),
        migrations.CreateModel(
            name='StageApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('decision', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شد'), ('rejected', 'رد شد')], default='pending', max_length=20, verbose_name='تصمیم')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم')),
                ('comment', models.TextField(blank=True, verbose_name='توضیح/دلیل رد')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_approvals', to=settings.AUTH_USER_MODEL, verbose_name='ارسال\u200cکننده')),
                ('sent_to_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_approvals', to='core.party', verbose_name='ارسال\u200cشده برای')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='projects.projectstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'درخواست تاییدیه مرحله',
                'verbose_name_plural': 'درخواست\u200cهای تاییدیه مرحله',
            },
        ),
        migrations.CreateModel(
            name='StageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='وضعیت قبلی')),
                ('to_status', models.CharField(max_length=20, verbose_name='وضعیت جدید')),
                ('comment', models.TextField(blank=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.projectstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'رویداد مرحله',
                'verbose_name_plural': 'رویدادهای مرحله',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ترتیب')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان داخلی مرحله')),
                ('client_label', models.CharField(blank=True, max_length=150, verbose_name='عنوانی که کارفرما می\u200cبیند')),
                ('responsible_role', models.CharField(blank=True, choices=[('manager', 'مدیر'), ('employee', 'تکنسین')], max_length=20, verbose_name='نقش مسئول')),
                ('approval_by', models.CharField(choices=[('none', 'بدون نیاز به تایید'), ('admin', 'مدیر'), ('partner', 'شریک تجاری'), ('owner', 'کارفرما/صاحب ملک'), ('choose_at_runtime', 'ادمین موقع ارسال انتخاب می\u200cکند')], default='none', max_length=20, verbose_name='نیازمند تایید توسط')),
                ('estimated_duration_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت\u200cزمان تخمینی (ساعت)')),
                ('client_visible', models.BooleanField(default=True, verbose_name='قابل نمایش به کارفرما')),
                ('allows_file_upload', models.BooleanField(default=False, verbose_name='امکان آپلود فایل در این مرحله')),
                ('on_reject_go_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_from', to='projects.workflowsteptemplate', verbose_name='در صورت رد، برگردد به این مرحله')),
                ('responsible_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='core.specialty', verbose_name='تخصص مورد نیاز')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projects.workflowtemplate', verbose_name='قالب گردش\u200cکار')),
            ],
            options={
                'verbose_name': 'مرحله قالب گردش\u200cکار',
                'verbose_name_plural': 'مراحل قالب گردش\u200cکار',
                'ordering': ['template', 'order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.AddField(
            model_name='projectstage',
            name='step_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_instances', to='projects.workflowsteptemplate', verbose_name='مرحله قالب مرجع'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='workflow_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.workflowtemplate', verbose_name='قالب گردش\u200cکار'),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.workflowtemplate', verbose_name='قالب گردش\u200cکار'),
        ),
    ]
