# Generated by Django 6.1.1 on 2026-09-19 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_workflowtemplate_remove_historicalproject_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='candidate_users',
            field=models.ManyToManyField(blank=True, related_name='candidate_stages', to=settings.AUTH_USER_MODEL, verbose_name='افراد واجد شرایط (تا زمانی که کسی کار را برندارد)'),
        ),
        migrations.AddField(
            model_name='workflowsteptemplate',
            name='default_assignee',
            field=models.ForeignKey(blank=True, help_text='اگر پر شود، این مرحله همیشه مستقیم به همین شخص ارجاع می\u200cشود بدون نیاز به Claim.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_assigned_steps', to=settings.AUTH_USER_MODEL, verbose_name='مسئول ثابت این مرحله (اختیاری)'),
        ),
    ]
