# Generated by Django 6.1.1 on 2026-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectstage_candidate_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='عنوان فایل'),
        ),
    ]
