# Generated by Django 6.1.1 on 2026-09-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('waiting_approval', 'در انتظار تایید'), ('rejected', 'رد شده / نیازمند اصلاح'), ('done', 'انجام\u200cشده'), ('suspended', 'معلق - در انتظار بررسی مدیر')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
