# Generated by Django 6.1.1 on 2026-09-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectstage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='kind',
            field=models.CharField(choices=[('dwg', 'فایل اتوکد (DWG)'), ('gcode', 'فایل جی\u200cکد (برش CNC)'), ('pdf', 'PDF'), ('image', 'عکس'), ('other', 'سایر')], max_length=20, verbose_name='نوع فایل'),
        ),
    ]
