# Generated by Django 6.1.1 on 2026-09-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_seed_default_workflow_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsteptemplate',
            name='requires_payment_selection',
            field=models.BooleanField(default=False, verbose_name='این مرحله نیازمند انتخاب روش پرداخت هم هست (نه فقط تایید ساده)'),
        ),
    ]
