# Generated by Django 6.1.1 on 2026-09-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_set_payment_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='estimated_end_date',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='guaranteed_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimated_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='guaranteed_end_date',
        ),
    ]
