# Generated by Django 6.1.1 on 2026-09-30 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_marginrule_value_type'),
        ('projects', '0012_remove_historicalproject_estimated_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='visit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بازدید'),
        ),
        migrations.AddField(
            model_name='project',
            name='visit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان بازدید'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_attachment',
            field=models.BooleanField(default=False, verbose_name='پیوست (بدون نسخه\u200cبندی)'),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='kind',
            field=models.CharField(choices=[('generic', 'عمومی'), ('visit', 'بازدید'), ('proforma', 'صدور پیش\u200cفاکتور'), ('design_initial', 'طراحی اولیه'), ('design_approval', 'تایید طرح اولیه'), ('gcode', 'جی\u200cکدگیری'), ('cutting', 'برش\u200cکاری'), ('shipping', 'ارسال'), ('install', 'نصب'), ('final_review', 'بازبینی نهایی')], default='generic', max_length=30, verbose_name='نوع رفتاری'),
        ),
        migrations.AddField(
            model_name='workflowsteptemplate',
            name='assign_to_project_creator',
            field=models.BooleanField(default=False, verbose_name='مسئول = ثبت\u200cکننده\u200cی پروژه'),
        ),
        migrations.AddField(
            model_name='workflowsteptemplate',
            name='kind',
            field=models.CharField(choices=[('generic', 'عمومی'), ('visit', 'بازدید'), ('proforma', 'صدور پیش\u200cفاکتور'), ('design_initial', 'طراحی اولیه'), ('design_approval', 'تایید طرح اولیه'), ('gcode', 'جی\u200cکدگیری'), ('cutting', 'برش\u200cکاری'), ('shipping', 'ارسال'), ('install', 'نصب'), ('final_review', 'بازبینی نهایی')], default='generic', max_length=30, verbose_name='نوع رفتاری مرحله'),
        ),
        migrations.CreateModel(
            name='ProjectServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار')),
                ('cost_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='میانگین موزون (اسنپ\u200cشات)')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='سود ٪ (اسنپ\u200cشات)')),
                ('line_total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع فروش (تومان)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_line_usages', to='catalog.item', verbose_name='کالا')),
                ('service_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.projectservice', verbose_name='خدمت پروژه')),
            ],
            options={
                'verbose_name': 'کالای زیر خدمت',
                'verbose_name_plural': 'کالاهای زیر خدمت',
            },
        ),
    ]
