# Generated by Django 6.1.1 on 2026-09-30 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_historicalproject_visit_at_project_visit_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={},
        ),
        migrations.AddField(
            model_name='projectfile',
            name='cut_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد برش (فقط جی\u200cکد)'),
        ),
        migrations.CreateModel(
            name='CutDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(verbose_name='شماره\u200cی برش')),
                ('done_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts_done', to='projects.projectfile', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'برش انجام\u200cشده',
                'verbose_name_plural': 'برش\u200cهای انجام\u200cشده',
                'constraints': [models.UniqueConstraint(fields=('file', 'index'), name='unique_cut_per_file')],
            },
        ),
    ]
