# Generated by Django 6.1.1 on 2026-09-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projectfile_options_projectfile_cut_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfile',
            options={'ordering': ['stage', '-version'], 'verbose_name': 'فایل پروژه', 'verbose_name_plural': 'فایل\u200cهای پروژه'},
        ),
    ]
