# Generated by Django 6.1.1 on 2026-10-01 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_marginrule_value_type'),
        ('projects', '0015_alter_projectfile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار')),
                ('cost_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='میانگین موزون (اسنپ\u200cشات)')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='سود ٪ (اسنپ\u200cشات)')),
                ('sale_total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع فروش (تومان)')),
                ('note', models.CharField(max_length=500, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_shipments', to='catalog.item', verbose_name='کالا')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_shipments', to='projects.project', verbose_name='پروژه')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_shipments', to='projects.projectstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'کالای اضافه\u200cی ارسال',
                'verbose_name_plural': 'کالاهای اضافه\u200cی ارسال',
            },
        ),
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار')),
                ('note', models.CharField(max_length=500, verbose_name='دلیل درخواست')),
                ('status', models.CharField(choices=[('requested', 'در انتظار انباردار'), ('issued', 'تحویل شد'), ('rejected', 'رد شد'), ('cancelled', 'لغو شد')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=500)),
                ('cost_total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بهای واقعی FIFO')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('sale_total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع فروش')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_requests', to='catalog.item', verbose_name='کالا')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='projects.project', verbose_name='پروژه')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_requests_made', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='projects.projectstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'درخواست قطعه',
                'verbose_name_plural': 'درخواست\u200cهای قطعه',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('part_shipping', 'ارسال قطعات جدید'), ('other', 'سایر')], max_length=30, verbose_name='نوع')),
                ('title', models.CharField(max_length=255, verbose_name='شرح')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_costs', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'هزینه\u200cی ثبت\u200cشده',
                'verbose_name_plural': 'هزینه\u200cهای ثبت\u200cشده',
            },
        ),
        migrations.CreateModel(
            name='InstallLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'خدمت'), ('material', 'کالا')], max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان (اسنپ\u200cشات)')),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('planned_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار پیش\u200cفاکتور')),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='مقدار واقعی')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='بهای واحد (اسنپ\u200cشات پیش\u200cفاکتور)')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='سود ٪ (اسنپ\u200cشات پیش\u200cفاکتور)')),
                ('status', models.CharField(choices=[('pending', 'ثبت\u200cنشده'), ('ok', 'نصب شد'), ('not_ok', 'نصب نشد')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, verbose_name='دلیل')),
                ('delta_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='اختلاف (+اضافه، −کسری)')),
                ('delta_sale', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='ارزش اختلاف (تومان)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='install_lines', to='catalog.item')),
                ('material_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='install_lines', to='projects.projectservicematerial')),
                ('service_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='install_lines', to='projects.projectservice')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_lines', to='projects.projectstage', verbose_name='مرحله')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ردیف نصب',
                'verbose_name_plural': 'ردیف\u200cهای نصب',
                'ordering': ['service_line_id', 'kind', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'service'), ('service_line__isnull', False)), fields=('stage', 'service_line'), name='uniq_install_service'), models.UniqueConstraint(condition=models.Q(('kind', 'material'), ('material_line__isnull', False)), fields=('stage', 'material_line'), name='uniq_install_material')],
            },
        ),
        migrations.CreateModel(
            name='ShipmentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('not_sent', 'ارسال نشد')], max_length=20, verbose_name='وضعیت')),
                ('reason', models.TextField(blank=True, verbose_name='دلیل ارسال\u200cنشدن')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='زمان')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_checks', to='projects.projectfile', verbose_name='فایل')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_checks', to='projects.projectstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'چک ارسال',
                'verbose_name_plural': 'چک\u200cهای ارسال',
                'constraints': [models.UniqueConstraint(fields=('stage', 'file'), name='unique_shipcheck_per_file')],
            },
        ),
    ]
