# Generated by Django 6 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_extrashipment_partrequest_projectcost_installline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='visit_at',
            new_name='visit_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='visit_at',
            new_name='visit_date',
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازدید'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ بازدید'),
        ),
    ]
