# Generated by Django 6.1.1 on 2026-10-01 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_and_alter_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='partrequest',
            name='photo',
            field=models.FileField(blank=True, upload_to='projects/parts/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='part_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='projects.partrequest'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='return_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_stages', to='projects.projectstage', verbose_name='بعد از تکمیل برگرد به'),
        ),
        migrations.AlterField(
            model_name='installline',
            name='delta_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='اختلاف (+کسری، −اضافه)'),
        ),
        migrations.AlterField(
            model_name='partrequest',
            name='cost_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بهای تمام\u200cشده'),
        ),
        migrations.AlterField(
            model_name='stageapproval',
            name='decision',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شد'), ('rejected', 'رد شد'), ('cancelled', 'لغو شد')], default='pending', max_length=20, verbose_name='تصمیم'),
        ),
    ]
