# Generated by Django 6.1.1 on 2026-10-02 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_partrequest_photo_projectcost_part_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extrashipment',
            name='disposed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تعیین تکلیف'),
        ),
        migrations.AddField(
            model_name='extrashipment',
            name='disposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تعیین\u200cکننده\u200cی تکلیف'),
        ),
        migrations.AddField(
            model_name='extrashipment',
            name='disposition',
            field=models.CharField(choices=[('pending', 'در انتظار تعیین تکلیف'), ('consumed', 'مصرف شد (از موجودی کم شد)'), ('returned', 'برگشت به انبار (بدون اثر بر موجودی)')], default='pending', max_length=20, verbose_name='تعیین تکلیف'),
        ),
    ]
