# Generated by Django 6.1.1 on 2026-10-03 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_extrashipment_disposed_at_extrashipment_disposed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExtraLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('extra', 'هزینه\u200cی اضافه'), ('discount', 'تخفیف')], default='extra', max_length=10, verbose_name='نوع')),
                ('title', models.CharField(max_length=200, verbose_name='شرح (روی پیش\u200cفاکتور)')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ واحد (تومان)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_lines', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'ردیف دستی پیش\u200cفاکتور',
                'verbose_name_plural': 'ردیف\u200cهای دستی پیش\u200cفاکتور',
                'ordering': ['pk'],
            },
        ),
    ]
