# Generated by Django 6.1.1 on 2026-10-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectextraline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrashipment',
            name='disposed_at',
        ),
        migrations.RemoveField(
            model_name='extrashipment',
            name='disposed_by',
        ),
        migrations.RemoveField(
            model_name='extrashipment',
            name='disposition',
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='kind',
            field=models.CharField(choices=[('labor', 'دستمزد'), ('transport', 'حمل و ایاب\u200cذهاب'), ('damage', 'خسارت'), ('part_shipping', 'ارسال قطعات جدید'), ('other', 'سایر')], max_length=30, verbose_name='نوع'),
        ),
    ]
