# Generated by Django 6.1.1 on 2026-09-17 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='عنوان مکان')),
                ('address_text', models.TextField(blank=True, verbose_name='آدرس به\u200cصورت متنی (دستی)')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شهر')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
            ],
            options={
                'verbose_name': 'موقعیت مکانی',
                'verbose_name_plural': 'موقعیت\u200cهای مکانی',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('party_type', models.CharField(choices=[('individual', 'شخص حقیقی'), ('company', 'شخص حقوقی (شرکت)')], max_length=20, verbose_name='نوع طرف\u200cحساب')),
                ('name', models.CharField(max_length=255, verbose_name='نام / نام شرکت')),
                ('brand_name', models.CharField(blank=True, max_length=255, verbose_name='نام برند/تجاری')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس دوم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('company_registration_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='شماره ثبت شرکت')),
                ('company_economic_code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='شناسه/کد اقتصادی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط (در صورت وجود)')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='core.location', verbose_name='موقعیت مکانی')),
            ],
            options={
                'verbose_name': 'طرف\u200cحساب',
                'verbose_name_plural': 'طرف\u200cحساب\u200cها',
            },
        ),
    ]
