# Generated by Django 6.1.1 on 2026-09-18 07:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalParty',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('party_type', models.CharField(choices=[('individual', 'شخص حقیقی'), ('company', 'شخص حقوقی (شرکت)')], max_length=20, verbose_name='نوع طرف\u200cحساب')),
                ('name', models.CharField(max_length=255, verbose_name='نام / نام شرکت')),
                ('brand_name', models.CharField(blank=True, max_length=255, verbose_name='نام برند/تجاری')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('secondary_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس دوم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('national_code', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('company_registration_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='شماره ثبت شرکت')),
                ('company_economic_code', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='شناسه/کد اقتصادی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط (در صورت وجود)')),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location', verbose_name='موقعیت مکانی')),
            ],
            options={
                'verbose_name': 'historical طرف\u200cحساب',
                'verbose_name_plural': 'historical طرف\u200cحساب\u200cها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
