# Generated by Django 6.1.1 on 2026-09-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='سمت')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('is_primary', models.BooleanField(default=False, verbose_name='رابط اصلی')),
            ],
            options={
                'verbose_name': 'رابط طرف\u200cحساب',
                'verbose_name_plural': 'رابط\u200cهای طرف\u200cحساب',
            },
        ),
        migrations.RemoveField(
            model_name='historicalparty',
            name='linked_user',
        ),
        migrations.RemoveField(
            model_name='historicalparty',
            name='party_type',
        ),
        migrations.RemoveField(
            model_name='party',
            name='linked_user',
        ),
        migrations.RemoveField(
            model_name='party',
            name='party_type',
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='credit_limit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سقف اعتبار (تومان)'),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='entity_type',
            field=models.CharField(choices=[('individual', 'شخص حقیقی'), ('company', 'شخص حقوقی (شرکت)')], default='individual', max_length=20, verbose_name='نوع شخص'),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='کارفرما'),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='is_contractor',
            field=models.BooleanField(default=False, verbose_name='پیمانکار'),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='حساب داخلی شرکت خودمان'),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='شریک تجاری'),
        ),
        migrations.AddField(
            model_name='historicalparty',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='تأمین\u200cکننده'),
        ),
        migrations.AddField(
            model_name='party',
            name='credit_limit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سقف اعتبار (تومان)'),
        ),
        migrations.AddField(
            model_name='party',
            name='entity_type',
            field=models.CharField(choices=[('individual', 'شخص حقیقی'), ('company', 'شخص حقوقی (شرکت)')], default='individual', max_length=20, verbose_name='نوع شخص'),
        ),
        migrations.AddField(
            model_name='party',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='کارفرما'),
        ),
        migrations.AddField(
            model_name='party',
            name='is_contractor',
            field=models.BooleanField(default=False, verbose_name='پیمانکار'),
        ),
        migrations.AddField(
            model_name='party',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='حساب داخلی شرکت خودمان'),
        ),
        migrations.AddField(
            model_name='party',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='شریک تجاری'),
        ),
        migrations.AddField(
            model_name='party',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='تأمین\u200cکننده'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('is_internal', True)), fields=('is_internal',), name='unique_internal_party'),
        ),
        migrations.AddField(
            model_name='partycontact',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.party', verbose_name='طرف\u200cحساب'),
        ),
    ]
