# Generated by Django 6.1.1 on 2026-10-04 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_internal_party_is_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال شمسی')),
                ('month', models.PositiveSmallIntegerField(verbose_name='ماه شمسی')),
                ('is_locked', models.BooleanField(default=True, verbose_name='بسته است')),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قفل ماه',
                'verbose_name_plural': 'قفل ماه\u200cها',
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_period_lock')],
            },
        ),
    ]
