# Generated by Django 6.1.1 on 2026-09-19 11:51

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_partycontact_remove_historicalparty_linked_user_and_more'),
        ('projects', '0003_workflowtemplate_remove_historicalproject_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاریخ بروزرسانی')),
                ('number', models.CharField(db_index=True, max_length=30, verbose_name='شماره فاکتور')),
                ('document_type', models.CharField(choices=[('proforma', 'پیش\u200cفاکتور'), ('final', 'فاکتور قطعی')], default='proforma', max_length=20, verbose_name='نوع سند')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال\u200cشده'), ('awaiting_approval', 'در انتظار تایید'), ('partially_paid', 'پرداخت ناقص'), ('paid', 'تسویه\u200cشده'), ('cancelled', 'لغوشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('address_snapshot', models.TextField(blank=True, verbose_name='آدرس (کپی\u200cشده در لحظه صدور)')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ کل (تومان)')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ پرداخت\u200cشده (محاسبه خودکار)')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='تاریخ عقد قرارداد')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تسویه کامل')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='شناسه یکتا')),
                ('pdf_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='فایل PDF')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('billed_party', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.party', verbose_name='طرف\u200cحساب فاکتور')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'historical فاکتور',
                'verbose_name_plural': 'historical فاکتورها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='شماره فاکتور')),
                ('document_type', models.CharField(choices=[('proforma', 'پیش\u200cفاکتور'), ('final', 'فاکتور قطعی')], default='proforma', max_length=20, verbose_name='نوع سند')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال\u200cشده'), ('awaiting_approval', 'در انتظار تایید'), ('partially_paid', 'پرداخت ناقص'), ('paid', 'تسویه\u200cشده'), ('cancelled', 'لغوشده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('address_snapshot', models.TextField(blank=True, verbose_name='آدرس (کپی\u200cشده در لحظه صدور)')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ کل (تومان)')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ پرداخت\u200cشده (محاسبه خودکار)')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='تاریخ عقد قرارداد')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تسویه کامل')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/', verbose_name='فایل PDF')),
                ('billed_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.party', verbose_name='طرف\u200cحساب فاکتور')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('service', 'خدمت'), ('material', 'متریال'), ('installation', 'هزینه نصب'), ('shipping', 'هزینه ارسال'), ('extra', 'هزینه مازاد'), ('discount', 'تخفیف')], max_length=20, verbose_name='نوع ردیف')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان (اسنپ\u200cشات)')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='قیمت واحد (تومان، برای تخفیف منفی وارد شود)')),
                ('cost_snapshot', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='بهای تمام\u200cشده (اسنپ\u200cشات برای گزارش سود)')),
                ('total', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='جمع ردیف (تومان)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ردیف فاکتور',
                'verbose_name_plural': 'ردیف\u200cهای فاکتور',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('entry_type', models.CharField(choices=[('debit', 'بدهکار (طرف\u200cحساب به ما بدهکار است)'), ('credit', 'بستانکار (طرف\u200cحساب طلبکار است)')], max_length=20, verbose_name='نوع')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ (تومان)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='شرح')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.party', verbose_name='طرف\u200cحساب')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'سند دفتر حساب',
                'verbose_name_plural': 'اسناد دفتر حساب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('method', models.CharField(choices=[('gateway', 'درگاه پرداخت'), ('card_to_card', 'کارت به کارت'), ('receipt', 'رسید واریز'), ('cheque', 'چک'), ('credit', 'اعتباری')], max_length=20, verbose_name='روش پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تاییدشده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری/تراکنش')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='تصویر رسید/فیش')),
                ('cheque_number', models.CharField(blank=True, max_length=30, verbose_name='شماره صیادی چک')),
                ('cheque_bank', models.CharField(blank=True, max_length=100, verbose_name='بانک')),
                ('cheque_due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید چک')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
