# Generated by Django 6.1.1 on 2026-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, verbose_name='توضیحات (به\u200cخصوص برای روش اعتباری)'),
        ),
    ]
