# Generated by Django 6.1.1 on 2026-09-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_historicalinvoice_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='ردیف\u200cهای دستی هنگام بازتولید ردیف\u200cها از روی پروژه حذف نمی\u200cشوند.', verbose_name='ردیف دستی'),
        ),
    ]
