# Generated by Django 6.1.1 on 2026-09-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoiceline_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='claimed_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='مبلغی که مشتری هنگام ثبت وارد کرده. مبلغ رسمی پرداخت همان «مبلغ» است که کارشناس از روی رسید تایید می\u200cکند.', max_digits=18, null=True, verbose_name='مبلغ اعلام\u200cشده توسط مشتری'),
        ),
    ]
