# Generated by Django 6.1.1 on 2026-10-03 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_claimed_amount'),
        ('projects', '0020_projectextraline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='settles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='finance.payment', verbose_name='اعتباری که این پرداخت وصول می\u200cکند'),
        ),
        migrations.CreateModel(
            name='AccountingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('settlement', 'تسویه\u200cی مصرف مواد'), ('stock_fix', 'اصلاح موجودی'), ('invoice_line', 'اصلاح فاکتور'), ('cost', 'هزینه'), ('credit', 'وصول اعتباری'), ('disposition', 'تعیین تکلیف قطعه\u200cی اضافه')], max_length=20, verbose_name='نوع')),
                ('text', models.CharField(max_length=500, verbose_name='شرح')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_events', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'رویداد حسابداری',
                'verbose_name_plural': 'رویدادهای حسابداری',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
