# Generated by Django 6.1.1 on 2026-10-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_settles_accountingevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='settles',
        ),
        migrations.AlterField(
            model_name='accountingevent',
            name='kind',
            field=models.CharField(choices=[('settlement', 'تسویه\u200cی مصرف مواد'), ('stock_fix', 'اصلاح موجودی'), ('invoice_line', 'اصلاح فاکتور'), ('cost', 'هزینه'), ('payment', 'ثبت پرداخت')], max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('gateway', 'درگاه پرداخت'), ('card_to_card', 'کارت به کارت'), ('receipt', 'رسید واریز'), ('cheque', 'چک'), ('credit', 'اعتباری'), ('cash', 'نقدی')], max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
