# Generated by Django 6.1.1 on 2026-10-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_payment_settles_alter_accountingevent_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingevent',
            name='kind',
            field=models.CharField(choices=[('settlement', 'تسویه\u200cی مصرف مواد'), ('stock_fix', 'اصلاح موجودی'), ('invoice_line', 'اصلاح فاکتور'), ('cost', 'هزینه'), ('payment', 'ثبت پرداخت'), ('period', 'قفل ماه')], max_length=20, verbose_name='نوع'),
        ),
    ]
