# Generated by Django 6.1.1 on 2026-10-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_accountingevent_kind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
    ]
