# Generated by Django 6.1.1 on 2026-09-16 16:19

import django.core.validators
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[utils.utils.validate_national_code], verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست (باید ۱۱ رقم و با 09 شروع شود، مثال: 09123456789)', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
