# Generated by Django 6.1.1 on 2026-09-17 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_national_code_alter_user_phone_number'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='core.specialty', verbose_name='تخصص\u200cها'),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('password_reset', 'فراموشی رمز عبور'), ('phone_verification', 'تایید شماره موبایل')], max_length=30, verbose_name='نوع کاربرد')),
                ('code_hash', models.CharField(max_length=128, verbose_name='هش کد')),
                ('is_used', models.BooleanField(default=False, verbose_name='مصرف شده')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان مصرف')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش ناموفق')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی درخواست\u200cدهنده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر (در صورت وجود)')),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف',
                'verbose_name_plural': 'کدهای یکبارمصرف',
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'is_used'], name='accounts_ot_phone_n_76ae90_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_2f08f4_idx')],
            },
        ),
    ]
