# Generated by Django 6.1.1 on 2026-09-18 07:41

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_specialties_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('manager', 'مدیر'), ('employee', 'تکنسین'), ('client', 'کارفرما')], default='employee', max_length=20, verbose_name='نقش کاربر')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست (باید ۱۱ رقم و با 09 شروع شود، مثال: 09123456789)', regex='^09\\d{9}$')], verbose_name='شماره موبایل')),
                ('national_code', models.CharField(blank=True, db_index=True, max_length=10, null=True, validators=[utils.utils.validate_national_code], verbose_name='کد ملی')),
                ('avatar', models.TextField(blank=True, max_length=100, null=True, verbose_name='تصویر پروفایل')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical کاربر',
                'verbose_name_plural': 'historical کاربران',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, max_length=150, verbose_name='نام\u200cکاربری وارد شده')),
                ('result', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق')], max_length=10, verbose_name='نتیجه')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent خام')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='مرورگر')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='سیستم\u200cعامل')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='نوع دستگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه ورود',
                'verbose_name_plural': 'تاریخچه\u200cی ورودها',
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_lo_user_id_ef3169_idx'), models.Index(fields=['ip_address', '-created_at'], name='accounts_lo_ip_addr_57e141_idx'), models.Index(fields=['result', '-created_at'], name='accounts_lo_result_b68b42_idx')],
            },
        ),
    ]
