# Generated by Django 6.1.1 on 2026-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_historicaluser_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='نیاز به تغییر رمز در ورود بعدی'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='نیاز به تغییر رمز در ورود بعدی'),
        ),
    ]
