# Generated by Django 6.1.1 on 2026-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_historicaluser_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر'), ('employee', 'تکنسین'), ('client', 'کارفرما')], default='client', max_length=20, verbose_name='نقش کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر'), ('employee', 'تکنسین'), ('client', 'کارفرما')], default='client', max_length=20, verbose_name='نقش کاربر'),
        ),
    ]
