# Generated by Django 6.1.1 on 2026-09-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_historicaluser_role_alter_user_role'),
        ('core', '0003_partycontact_remove_historicalparty_linked_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.party', verbose_name='طرف\u200cحساب مرتبط (برای نقش کارفرما/شریک تجاری)'),
        ),
        migrations.AddField(
            model_name='user',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.party', verbose_name='طرف\u200cحساب مرتبط (برای نقش کارفرما/شریک تجاری)'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر'), ('employee', 'تکنسین'), ('client', 'کارفرما'), ('partner', 'شریک تجاری')], default='client', max_length=20, verbose_name='نقش کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'مدیر'), ('employee', 'تکنسین'), ('client', 'کارفرما'), ('partner', 'شریک تجاری')], default='client', max_length=20, verbose_name='نقش کاربر'),
        ),
    ]
