# Generated by Django 6.1.1 on 2026-10-04 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_historicaluser_party_user_party_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(verbose_name='آخرین زمان دیده\u200cشدن')),
                ('last_path', models.CharField(blank=True, max_length=300, verbose_name='آخرین صفحه')),
                ('view_name', models.CharField(blank=True, max_length=100, verbose_name='نام صفحه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حضور کاربر',
                'verbose_name_plural': 'حضور کاربران',
            },
        ),
    ]
