# Generated by Django 6.1.1 on 2026-09-19 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_partycontact_remove_historicalparty_linked_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('is_default', models.BooleanField(default=False, verbose_name='انبار پیش\u200cفرض')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='شماره فاکتور خرید')),
                ('purchased_at', models.DateTimeField(verbose_name='تاریخ خرید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.party', verbose_name='فروشنده/تأمین\u200cکننده')),
            ],
            options={
                'verbose_name': 'سند خرید',
                'verbose_name_plural': 'اسناد خرید',
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='بهای خرید واحد (تومان)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.item', verbose_name='کالا')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.purchase', verbose_name='سند خرید')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.warehouse', verbose_name='انبار مقصد')),
            ],
            options={
                'verbose_name': 'ردیف خرید',
                'verbose_name_plural': 'ردیف\u200cهای خرید',
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('qty_in', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار ورودی اولیه')),
                ('qty_remaining', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار باقی\u200cمانده')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='بهای تمام\u200cشده واحد (تومان)')),
                ('received_at', models.DateTimeField(verbose_name='تاریخ ورود به انبار')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.item', verbose_name='کالا')),
                ('purchase_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='inventory.purchaseline', verbose_name='ردیف خرید مبدأ')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'لات موجودی',
                'verbose_name_plural': 'لات\u200cهای موجودی',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('movement_type', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج (مصرف)'), ('return', 'برگشت به انبار'), ('adjust', 'اصلاح دستی'), ('transfer', 'انتقال بین انبارها')], max_length=20, verbose_name='نوع حرکت')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='بهای واحد در لحظه حرکت (تومان)')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.item', verbose_name='کالا')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot', verbose_name='لات')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'حرکت انبار',
                'verbose_name_plural': 'حرکت\u200cهای انبار',
                'indexes': [models.Index(fields=['item', '-created_at'], name='inventory_s_item_id_384e17_idx')],
            },
        ),
    ]
