# Generated by Django 6.1.1 on 2026-09-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='purchases/invoices/', verbose_name='فایل فاکتور خرید'),
        ),
    ]
