# Generated by Django 6.1.1 on 2026-10-03 07:32

from django.db import migrations, models


def backfill_direction(apps, schema_editor):
    StockMovement = apps.get_model("inventory", "StockMovement")
    StockMovement.objects.filter(movement_type="out").update(direction="out")
    for m in StockMovement.objects.filter(movement_type="adjust").order_by("id"):
        first_id = StockMovement.objects.filter(lot_id=m.lot_id).order_by("id").values_list("id", flat=True).first()
        if first_id != m.id:   # اولین حرکت هر لات همان ورود است؛ بقیه‌ی adjustها کاهش‌اند
            StockMovement.objects.filter(pk=m.pk).update(direction="out")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchase_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='direction',
            field=models.CharField(choices=[('in', 'افزایش موجودی'), ('out', 'کاهش موجودی')], default='in', max_length=3, verbose_name='جهت اثر روی موجودی'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'ورود (خرید)'), ('out', 'خروج (مصرف)'), ('return', 'برگشت به انبار'), ('adjust', 'اصلاح دستی'), ('transfer', 'انتقال بین انبارها'), ('opening', 'موجودی اولیه')], max_length=20, verbose_name='نوع حرکت'),
        ),
        migrations.RunPython(backfill_direction, migrations.RunPython.noop),
    ]
