# Generated by Django 6.1.1 on 2026-10-03 11:10

from django.db import migrations


def reclassify(apps, schema_editor):
    StockMovement = apps.get_model("inventory", "StockMovement")
    # ورودی‌های بدون ردیف خرید = موجودی اولیه (قبل از افزودن نوع «موجودی اولیه» با نوع خرید ثبت شده بودند)
    StockMovement.objects.filter(movement_type="in", lot__purchase_line__isnull=True).update(movement_type="opening")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_direction_and_more'),
    ]

    operations = [
        migrations.RunPython(reclassify, migrations.RunPython.noop),
    ]
