"""
Django settings for FaraBakhsh project (configured in package 'config').

Generated by 'django-admin startproject' using Django 6.1.1.
"""

import os
import sys
from pathlib import Path
import environ
from django.urls import reverse_lazy
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Take environment variables from .env file
env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    SECRET_KEY = env('SECRET_KEY', default='django-insecure-dev-fallback-key-only-for-debugging')
else:
    SECRET_KEY = env('SECRET_KEY')  # Raises ImproperlyConfigured in production if SECRET_KEY is missing

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost', 'farabakhshtahvie.com', 'www.farabakhshtahvie.com'])


# Application definition

INSTALLED_APPS = [
    # Django Unfold Admin Theme (Must be before django.contrib.admin)
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.simple_history',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Third-party packages
    'rest_framework',
    'django_htmx',
    'storages',
    'simple_history',
    'axes',
    # Local apps
    'core',
    'accounts',
    'catalog',
    'inventory',
    'projects',
    'finance',
    'notifications',
    'utils',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.ForcePasswordChangeMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='FaraBakhsh'),
        'USER': env('DB_USER', default='FaraBakhsh'),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env.int('DB_PORT', default=5432),
    }
}

if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


# Redis Cache configuration
# https://docs.djangoproject.com/en/6.1/topics/cache/

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/0'),
    }
}


# Signed Cookie Session Engine
# https://docs.djangoproject.com/en/6.1/topics/http/sessions/#using-cookie-based-sessions

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = 'farabakhsh_sessionid'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS


# Django REST Framework configuration
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}


# Static files (CSS, JavaScript, Images) -> Kept Local
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media Files & Storage configuration (Local or ArvanCloud Object Storage)
# https://django-storages.readthedocs.io/

USE_ARVANCLOUD_MEDIA = env.bool('USE_ARVANCLOUD_MEDIA', default=False)

if USE_ARVANCLOUD_MEDIA:
    AWS_ACCESS_KEY_ID = env('ARVANCLOUD_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('ARVANCLOUD_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('ARVANCLOUD_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env('ARVANCLOUD_S3_ENDPOINT_URL', default='https://s3.ir-thr-at1.arvanstorage.ir')
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False  # Public read URLs by default
    AWS_S3_ADDRESSING_STYLE = 'virtual'  # Use virtual-host style instead of path-style
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'public, max-age=2592000',  # 30 days cache for media files
    }

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "addressing_style": AWS_S3_ADDRESSING_STYLE,
                "file_overwrite": AWS_S3_FILE_OVERWRITE,
                "default_acl": AWS_DEFAULT_ACL,
                "querystring_auth": AWS_QUERYSTRING_AUTH,
                "object_parameters": AWS_S3_OBJECT_PARAMETERS,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_ENDPOINT_URL.replace('https://', '')}/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Configuration (Django 6.1 MAILERS specification)
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS': {} if DEBUG else {
            'host': env('EMAIL_HOST', default=''),
            'port': env.int('EMAIL_PORT', default=587),
            'use_tls': env.bool('EMAIL_USE_TLS', default=True),
            'username': env('EMAIL_HOST_USER', default=''),
            'password': env('EMAIL_HOST_PASSWORD', default=''),
        },
    },
}


AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_FAILURE_LIMIT = env.int('AXES_FAILURE_LIMIT', default=5)
AXES_COOLOFF_TIME = env.int('AXES_COOLOFF_TIME', default=1)  # hours

# SMS.ir Configuration
SMS_IR_API_KEY = env('SMS_IR_API_KEY', default='')
SMS_IR_LINE_NUMBER = env('SMS_IR_LINE_NUMBER', default='')
SMS_OTP_TEMPLATE_ID = env.int('SMS_OTP_TEMPLATE_ID', default=0)
SMS_INVOICE_TEMPLATE_ID = env.int('SMS_INVOICE_TEMPLATE_ID', default=0)

# Najva Push Notification Configuration
NAJVA_API_KEY = env('NAJVA_API_KEY', default='')
NAJVA_WEBSITE_ID = env('NAJVA_WEBSITE_ID', default='')
NAJVA_SEND_URL = env('NAJVA_SEND_URL', default='https://push.najva.com/v1/send/token/')

# Site URL for tracking links
SITE_BASE_URL = env('SITE_BASE_URL', default='https://farabakhshtahvie.com')
SMS_IR_SANDBOX_API_KEY = env('SMS_IR_SANDBOX_API_KEY', default='')  # فقط برای تست‌ها

# OTP Configuration
OTP_LENGTH = env.int('OTP_LENGTH', default=5)
OTP_EXPIRY_MINUTES = env.int('OTP_EXPIRY_MINUTES', default=2)

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'home'


# Django Unfold Admin Configuration
# https://github.com/unfoldadmin/django-unfold

UNFOLD = {
    "SITE_TITLE": "سامانه مدیریت فرابخش",
    "SITE_HEADER": "فرابخش",
    "SITE_SUBHEADER": "پنل اختصاصی مدیریت تهویه مطبوع",
    "DASHBOARD_CALLBACK": None,
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": None,
    "STYLES": [
        lambda request: static("css/admin_custom.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/admin_theme.js"),
    ],
    "BORDER_RADIUS": "12px",
    "COLORS": {
        "primary": {
            "50": "240 253 250",
            "100": "204 251 241",
            "200": "153 246 228",
            "300": "94 234 212",
            "400": "45 212 191",
            "500": "20 184 166",
            "600": "13 148 136",
            "700": "15 118 110",
            "800": "17 94 89",
            "900": "19 78 74",
            "950": "4 47 46",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "کاربران و احراز هویت",
                "separator": True,
                "items": [
                    {"title": "کاربران", "icon": "people", "link": reverse_lazy("admin:accounts_user_changelist")},
                    {"title": "تاریخچه‌ی ورودها", "icon": "history", "link": reverse_lazy("admin:accounts_loginhistory_changelist")},
                    {"title": "کدهای یکبارمصرف", "icon": "password", "link": reverse_lazy("admin:accounts_otpcode_changelist")},
                    {"title": "گروه‌ها", "icon": "lock", "link": reverse_lazy("admin:auth_group_changelist")},
                ],
            },
            {
                "title": "طرف‌حساب و پروژه‌ها",
                "separator": True,
                "items": [
                    {"title": "طرف‌حساب‌ها", "icon": "business", "link": reverse_lazy("admin:core_party_changelist")},
                    {"title": "تخصص‌ها", "icon": "engineering", "link": reverse_lazy("admin:core_specialty_changelist")},
                    {"title": "موقعیت‌های مکانی", "icon": "location_on", "link": reverse_lazy("admin:core_location_changelist")},
                    {"title": "پروژه‌ها", "icon": "work", "link": reverse_lazy("admin:projects_project_changelist")},
                ],
            },
            {
                "title": "کاتالوگ و انبار",
                "separator": True,
                "items": [
                    {"title": "خدمات", "icon": "handyman", "link": reverse_lazy("admin:catalog_service_changelist")},
                    {"title": "کالاها (متریال/قطعات)", "icon": "inventory_2", "link": reverse_lazy("admin:catalog_item_changelist")},
                    {"title": "اسناد خرید", "icon": "shopping_cart", "link": reverse_lazy("admin:inventory_purchase_changelist")},
                    {"title": "انبارها", "icon": "warehouse", "link": reverse_lazy("admin:inventory_warehouse_changelist")},
                ],
            },
            {
                "title": "گردش‌کار پروژه",
                "separator": True,
                "items": [
                    {"title": "قالب‌های گردش‌کار", "icon": "account_tree", "link": reverse_lazy("admin:projects_workflowtemplate_changelist")},
                ],
            },
            {
                "title": "مالی",
                "separator": True,
                "items": [
                    {"title": "فاکتورها", "icon": "receipt_long", "link": reverse_lazy("admin:finance_invoice_changelist")},
                    {"title": "پرداخت‌ها", "icon": "payments", "link": reverse_lazy("admin:finance_payment_changelist")},
                    {"title": "دفتر حساب", "icon": "account_balance", "link": reverse_lazy("admin:finance_ledgerentry_changelist")},
                ],
            },
            {
                "title": "اطلاع‌رسانی‌ها",
                "separator": True,
                "items": [
                    {"title": "اطلاع‌رسانی‌ها", "icon": "notifications", "link": reverse_lazy("admin:notifications_notification_changelist")},
                    {"title": "سیاست‌های اطلاع‌رسانی", "icon": "rule", "link": reverse_lazy("admin:notifications_notificationpolicy_changelist")},
                    {"title": "رویدادهای کلیک", "icon": "ads_click", "link": reverse_lazy("admin:notifications_notificationclickevent_changelist")},
                    {"title": "دستگاه‌های پوش", "icon": "smartphone", "link": reverse_lazy("admin:utils_pushdevice_changelist")},
                ],
            },
        ],
    },
}




