# Generated by Django 6.1.1 on 2026-09-19 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دسته')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.itemcategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی کالا',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای کالا',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('item_type', models.CharField(choices=[('material', 'متریال'), ('part', 'قطعه'), ('consumable', 'مصرفی')], max_length=20, verbose_name='نوع کالا')),
                ('unit', models.CharField(choices=[('meter', 'متر'), ('sqm', 'متر مربع'), ('cbm', 'متر مکعب'), ('liter', 'لیتر'), ('kg', 'کیلوگرم'), ('piece', 'عدد')], max_length=20, verbose_name='واحد سنجش')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حداقل موجودی برای هشدار')),
                ('moving_average_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='میانگین موزون قیمت (خودکار)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_items', to=settings.AUTH_USER_MODEL, verbose_name='مسئول هشدار موجودی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.itemcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'کالا (متریال/قطعه)',
                'verbose_name_plural': 'کالاها (متریال/قطعات)',
            },
        ),
        migrations.CreateModel(
            name='MarginRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('item', 'کالای مشخص'), ('category', 'دسته\u200cبندی'), ('global', 'سراسری')], max_length=20, verbose_name='محدوده اعمال')),
                ('value_type', models.CharField(choices=[('percent', 'درصد'), ('fixed', 'مبلغ ثابت (تومان)')], max_length=20, verbose_name='نوع مقدار')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مقدار')),
                ('valid_from', models.DateTimeField(verbose_name='اعتبار از تاریخ')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='اعتبار تا تاریخ (خالی=بدون انقضا)')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='اولویت')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='margin_rules', to='catalog.itemcategory', verbose_name='دسته\u200cبندی')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='margin_rules', to='catalog.item', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'قانون سود',
                'verbose_name_plural': 'قوانین سود',
                'ordering': ['-priority', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=255, verbose_name='نام خدمت')),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='کد خدمت')),
                ('unit', models.CharField(blank=True, choices=[('meter', 'متر'), ('sqm', 'متر مربع'), ('cbm', 'متر مکعب'), ('liter', 'لیتر'), ('kg', 'کیلوگرم'), ('piece', 'عدد')], max_length=20, verbose_name='واحد سنجش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.service', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='ServiceBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_unit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='مقدار به ازای هر واحد خدمت')),
                ('waste_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد ضایعات')),
                ('is_optional', models.BooleanField(default=False, verbose_name='اختیاری')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_services', to='catalog.item', verbose_name='کالا')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='catalog.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'متریال مورد نیاز خدمت',
                'verbose_name_plural': 'متریال\u200cهای مورد نیاز خدمات',
                'unique_together': {('service', 'item')},
            },
        ),
    ]
