# Generated by Django 6.1.1 on 2026-09-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='به\u200cصورت جفت برچسب-مقدار، مثلاً: {"جنس": "گالوانیزه", "ضخامت ورق": "0.6 تا 1.2 میلیمتر", "قطر": "100 تا 1600 میلیمتر", "نوع اتصال": "کوپلر یا فلنج"}', verbose_name='مشخصات فنی'),
        ),
    ]
