# Generated by Django 6.1.1 on 2026-09-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginrule',
            name='value_type',
            field=models.CharField(choices=[('percent', 'درصد')], default='percent', help_text='سود همیشه درصدی است', max_length=20, verbose_name='نوع مقدار'),
        ),
    ]
