# Generated by Django 6.1.1 on 2026-10-08 08:46

import django.db.models.deletion
import messenger.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('handle', models.CharField(blank=True, max_length=24)),
                ('avatar', models.FileField(blank=True, max_length=200, upload_to=messenger.models.avatar_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل پیام\u200cرسان',
                'verbose_name_plural': 'پروفایل\u200cهای پیام\u200cرسان',
                'constraints': [models.UniqueConstraint(condition=models.Q(('handle', ''), _negated=True), fields=('handle',), name='uniq_messenger_handle')],
            },
        ),
    ]
