# Generated by Django 6.1.1 on 2026-09-16 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام دستگاه')),
                ('registration_id', models.TextField(unique=True, verbose_name='شناسه توکن دستگاه (Push Token)')),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شناسه یکتای دستگاه')),
                ('type', models.CharField(choices=[('web', 'وب (Web)'), ('android', 'اندروید (Android)'), ('ios', 'آی او اس (iOS)')], default='web', max_length=10, verbose_name='نوع دستگاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرورگر')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='سیستم عامل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دستگاه پوش نوتیفیکیشن',
                'verbose_name_plural': 'دستگاه\u200cهای پوش نوتیفیکیشن',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['registration_id'], name='utils_pushd_registr_e8320f_idx'), models.Index(fields=['user', 'is_active'], name='utils_pushd_user_id_ba12c5_idx'), models.Index(fields=['type', 'is_active'], name='utils_pushd_type_7d010f_idx')],
            },
        ),
    ]
