# Generated by Django 6.1.1 on 2026-09-17 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('invoice_issued', 'صدور پیش\u200cفاکتور'), ('progress_update', 'پیشرفت مراحل کار'), ('manual', 'پیام دستی')], max_length=30, unique=True, verbose_name='نوع پیام')),
                ('channel_policy', models.CharField(choices=[('sms_only', 'فقط پیامک'), ('push_only', 'فقط پوش'), ('push_and_sms', 'پوش و پیامک با هم'), ('push_then_sms_fallback', 'پوش، اگه دیده نشد پیامک')], max_length=30, verbose_name='سیاست کانال')),
                ('fallback_after_minutes', models.PositiveIntegerField(default=15, verbose_name='مهلت قبل از پیامک جایگزین (دقیقه)')),
            ],
            options={
                'verbose_name': 'سیاست اطلاع\u200cرسانی',
                'verbose_name_plural': 'سیاست\u200cهای اطلاع\u200cرسانی',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا')),
                ('notification_type', models.CharField(choices=[('invoice_issued', 'صدور پیش\u200cفاکتور'), ('progress_update', 'پیشرفت مراحل کار'), ('manual', 'پیام دستی')], db_index=True, max_length=30, verbose_name='نوع پیام')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('real_target_url', models.URLField(blank=True, verbose_name='لینک مقصد واقعی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال'), ('push_sent', 'پوش ارسال شد'), ('seen', 'دیده شد'), ('sms_sent', 'پیامک ارسال شد'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پوش')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیامک')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان دیده\u200cشدن')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'اطلاع\u200cرسانی',
                'verbose_name_plural': 'اطلاع\u200cرسانی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('push', 'پوش'), ('sms', 'پیامک')], max_length=10, verbose_name='کانال')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان کلیک')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='notifications.notification', verbose_name='اطلاع\u200cرسانی')),
            ],
            options={
                'verbose_name': 'رویداد کلیک',
                'verbose_name_plural': 'رویدادهای کلیک',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'seen_at'], name='notificatio_status_21db00_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_content_type', 'related_object_id'], name='notificatio_related_3a0597_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationclickevent',
            index=models.Index(fields=['notification', 'clicked_at'], name='notificatio_notific_5d182b_idx'),
        ),
    ]
