# Generated by Django 6.1.1 on 2026-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده\u200cی اضافی برای تمپلیت'),
        ),
    ]
