# Generated by Django 6.1.1 on 2026-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invoice_issued', 'صدور پیش\u200cفاکتور'), ('progress_update', 'پیشرفت مراحل کار'), ('low_stock', 'کمبود موجودی انبار'), ('manual', 'پیام دستی')], db_index=True, max_length=30, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='notificationpolicy',
            name='notification_type',
            field=models.CharField(choices=[('invoice_issued', 'صدور پیش\u200cفاکتور'), ('progress_update', 'پیشرفت مراحل کار'), ('low_stock', 'کمبود موجودی انبار'), ('manual', 'پیام دستی')], max_length=30, unique=True, verbose_name='نوع پیام'),
        ),
    ]
