# Generated by Django 6.1.1 on 2026-09-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='short_code',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True, verbose_name='کد کوتاه لینک'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='real_target_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='لینک مقصد واقعی'),
        ),
    ]
