# Generated by Django 6.1.1 on 2026-10-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_seed_stage_approval_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invoice_issued', 'صدور پیش\u200cفاکتور'), ('progress_update', 'پیشرفت مراحل کار'), ('low_stock', 'کمبود موجودی انبار'), ('manual', 'پیام دستی'), ('stage_approval_request', 'درخواست تایید مرحله'), ('stage_assigned', 'کار جدید'), ('part_request', 'درخواست قطعه')], db_index=True, max_length=30, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='notificationpolicy',
            name='notification_type',
            field=models.CharField(choices=[('invoice_issued', 'صدور پیش\u200cفاکتور'), ('progress_update', 'پیشرفت مراحل کار'), ('low_stock', 'کمبود موجودی انبار'), ('manual', 'پیام دستی'), ('stage_approval_request', 'درخواست تایید مرحله'), ('stage_assigned', 'کار جدید'), ('part_request', 'درخواست قطعه')], max_length=30, unique=True, verbose_name='نوع پیام'),
        ),
    ]
