# Generated by Django 6.1.1 on 2026-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار ارسال'), ('push_sent', 'پوش ارسال شد'), ('seen', 'دیده شد'), ('sms_sent', 'پیامک ارسال شد'), ('failed', 'ناموفق'), ('in_app', 'فقط داخل برنامه')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
