# Generated by Django 6.1.1 on 2026-10-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_notification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='error_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invoice_issued', 'صدور پیش\u200cفاکتور'), ('progress_update', 'پیشرفت مراحل کار'), ('low_stock', 'کمبود موجودی انبار'), ('manual', 'پیام دستی'), ('stage_approval_request', 'درخواست تایید مرحله'), ('stage_assigned', 'کار جدید'), ('part_request', 'درخواست قطعه'), ('broadcast', 'پیام همگانی')], db_index=True, max_length=30, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='notificationpolicy',
            name='notification_type',
            field=models.CharField(choices=[('invoice_issued', 'صدور پیش\u200cفاکتور'), ('progress_update', 'پیشرفت مراحل کار'), ('low_stock', 'کمبود موجودی انبار'), ('manual', 'پیام دستی'), ('stage_approval_request', 'درخواست تایید مرحله'), ('stage_assigned', 'کار جدید'), ('part_request', 'درخواست قطعه'), ('broadcast', 'پیام همگانی')], max_length=30, unique=True, verbose_name='نوع پیام'),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('push', 'پوش'), ('sms', 'پیامک')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField()),
                ('link_path', models.CharField(blank=True, max_length=300)),
                ('icon_name', models.CharField(blank=True, max_length=60)),
                ('image_name', models.CharField(blank=True, max_length=60)),
                ('ttl_hours', models.PositiveSmallIntegerField(default=24)),
                ('audience_kind', models.CharField(max_length=20)),
                ('audience_ids', models.JSONField(blank=True, default=list)),
                ('audience_label', models.CharField(max_length=255)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('is_test', models.BooleanField(default=False)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام همگانی',
                'verbose_name_plural': 'پیام\u200cهای همگانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.broadcast'),
        ),
    ]
