# Generated by Django 6.1.1 on 2026-10-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_notification_error_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='buttons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
